// COPYRIGHT_BEGIN
//  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
//  
//  Copyright (C) 2008-2013, Cable Television Laboratories, Inc. 
//  
//  This software is available under multiple licenses: 
//  
//  (1) BSD 2-clause 
//   Redistribution and use in source and binary forms, with or without modification, are
//   permitted provided that the following conditions are met:
//        ·Redistributions of source code must retain the above copyright notice, this list 
//             of conditions and the following disclaimer.
//        ·Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
//             and the following disclaimer in the documentation and/or other materials provided with the 
//             distribution.
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
//   TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
//   PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
//   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
//   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
//   THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  
//  (2) GPL Version 2
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, version 2. This program is distributed
//   in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
//   even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//   PURPOSE. See the GNU General Public License for more details.
//  
//   You should have received a copy of the GNU General Public License along
//   with this program.If not, see<http:www.gnu.org/licenses/>.
//  
//  (3)CableLabs License
//   If you or the company you represent has a separate agreement with CableLabs
//   concerning the use of this code, your rights and obligations with respect
//   to this code shall be as set forth therein. No license is granted hereunder
//   for any other purpose.
//  
//   Please contact CableLabs if you need additional information or 
//   have any questions.
//  
//       CableLabs
//       858 Coal Creek Cir
//       Louisville, CO 80027-9750
//       303 661-9100
// COPYRIGHT_END

package org.cablelabs.impl.util;

import org.ocap.system.event.ErrorEvent;

/**
 * <code>SysInfoEvent</code> is an implementation-specific subclass of
 * <code>ErrorEvent</code>. It is used to log informational events that occur
 * during the operation of the stack.
 * 
 * @author Aaron Kamienski
 * 
 * @see SystemEventUtil#logEvent(String)
 * @see SystemEventUtil#logEvent(int, String)
 */
public class SysInfoEvent extends ErrorEvent
{

    /**
     * Class constructor specifying the event type code and readable message.
     * 
     * @param typeCode
     *            Unique error type code.
     * 
     * @param message
     *            Readable error message.
     * 
     * @throws IllegalArgumentException
     *             should not be thrown from privileged blocks
     */
    public SysInfoEvent(int typeCode, String message) throws IllegalArgumentException
    {
        super(typeCode, message);
    }

    /**
     * Class constructor specifying the event type code, and throwable
     * condition. The message is derived from the Throwable object. The
     * 
     * @param typeCode
     *            The unique error type code.
     * @param throwable
     *            A throwable object that was generated by the implementation or
     *            an application in response to an informational or error event,
     *            or by the implementation when a call made by an application
     *            throws an exception that isn't caught by the application.
     * 
     * @throws IllegalArgumentException
     *             should not be thrown from privileged blocks
     */
    /*
     * public SysInfoEvent(int typeCode, Throwable throwable) throws
     * IllegalArgumentException { super(typeCode, throwable); }
     */

    /**
     * This constructor is provided for internal use by OCAP implementations;
     * applications SHOULD NOT call it.
     * 
     * @param typeCode
     *            - The unique error type code.
     * @param message
     *            - Readable message specific to the event generator.
     * @param stacktrace
     *            - Stacktrace taken from a Throwable object or null if no
     *            Throwable used.
     * @param throwableClasses
     *            - The class hierarchy list from a Throwable object or null if
     *            no Throwable used.
     * @param date
     *            - Event date in milli-seconds from midnight January 1, 1970
     *            GMT.
     * @param appId
     *            - The Id of the application logging the event.
     * 
     * @throws SecurityException
     *             if this constructor is called by any application.
     */
    /*
     * public SysInfoEvent(int typeCode, String message, String stacktrace,
     * String[] throwableClasses, long date, AppID appId) throws
     * SecurityException { super(typeCode, message, stacktrace,
     * throwableClasses, date, appId); }
     */
}
