 // COPYRIGHT_BEGIN
 //  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 //  
 //  Copyright (C) 2008-2013, Cable Television Laboratories, Inc. 
 //  
 //  This software is available under multiple licenses: 
 //  
 //  (1) BSD 2-clause 
 //   Redistribution and use in source and binary forms, with or without modification, are
 //   permitted provided that the following conditions are met:
 //        ·Redistributions of source code must retain the above copyright notice, this list 
 //             of conditions and the following disclaimer.
 //        ·Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
 //             and the following disclaimer in the documentation and/or other materials provided with the 
 //             distribution.
 //   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 //   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
 //   TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
 //   PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 //   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 //   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 //   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 //   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
 //   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 //   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
 //   THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 //  
 //  (2) GPL Version 2
 //   This program is free software; you can redistribute it and/or modify
 //   it under the terms of the GNU General Public License as published by
 //   the Free Software Foundation, version 2. This program is distributed
 //   in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 //   even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 //   PURPOSE. See the GNU General Public License for more details.
 //  
 //   You should have received a copy of the GNU General Public License along
 //   with this program.If not, see<http:www.gnu.org/licenses/>.
 //  
 //  (3)CableLabs License
 //   If you or the company you represent has a separate agreement with CableLabs
 //   concerning the use of this code, your rights and obligations with respect
 //   to this code shall be as set forth therein. No license is granted hereunder
 //   for any other purpose.
 //  
 //   Please contact CableLabs if you need additional information or 
 //   have any questions.
 //  
 //       CableLabs
 //       858 Coal Creek Cir
 //       Louisville, CO 80027-9750
 //       303 661-9100
 // COPYRIGHT_END
 

package com.tvworks.plateval.fundamental;

import com.tvworks.plateval.TestCaseSet;
import com.tvworks.plateval.format.PlatformInformationRepository;
import com.tvworks.plateval.framework.TestCase;
import com.tvworks.plateval.util.ResultLog;

public class InstanceVariableWrite implements TestCase
{
   public static void touch()
   {      
   }
   
   public void run()
   {
      long runTime, totalRunTime;
      int count, totalCount, loopCount;
      
      loopCount= 0;
      totalCount= 0;
      totalRunTime= 0;
      count= 1000;
      for(;;)
      {
         ++loopCount;         
         runTime= doRun(count);
         totalRunTime += runTime;
         totalCount += count;
         count *= 2;
         if ( totalRunTime > 30000 )
         {
            break;
         }
         Thread.yield();
      }
      
      ResultLog.getInstance().add( TestCaseSet.TEST_InstanceVariableWrite, totalCount, loopCount, totalRunTime );
   }
   
   private int mA0;
   private int mA1;
   private int mA2;
   private int mA3;
   private int mA4;
   private int mA5;
   private int mA6;
   private int mA7;
   private int mA8;
   private int mA9;
   public long doRun(int count)
   {
      long startTime, endTime, runTime;

      startTime= System.currentTimeMillis();
      while( count-- > 0 )
      {
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
         mA0=  0;
         mA1=  1;
         mA2=  2;
         mA3=  3;
         mA4=  4;
         mA5=  5;
         mA6= -1;
         mA7=  0;
         mA8=  1;
         mA9=  2;
         mA0=  3;
         mA1=  4;
         mA2=  5;
         mA3= -1;
         mA4=  0;
         mA5=  1;
         mA6=  2;
         mA7=  3;
         mA8=  4;
         mA9=  5;
         mA0= -1;
         mA1=  0;
         mA2=  1;
         mA3=  2;
         mA4=  3;
         mA5=  4;
         mA6=  5;         
         mA7= -1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  2;
         mA5=  3;
         mA6=  4;
         mA7=  5;
         mA8= -1;
         mA9=  0;
         mA0=  1;
         mA1=  2;
         mA2=  3;
         mA3=  4;
         mA4=  5;
         mA5= -1;
         mA6=  0;
         mA7=  1;
         mA8=  2;
         mA9=  3;
         mA0=  4;
         mA1=  5;
         mA2= -1;
         mA3=  0;
         mA4=  1;
         mA5=  2;
         mA6=  3;
         mA7=  4;
         mA8=  5;
         mA9= -1;
      }
      endTime= System.currentTimeMillis();
      runTime= endTime-startTime;
      
      return runTime;
   }

   public static void format( PlatformInformationRepository pir, StringBuffer sb, int data1, int data2, long data3 )
   {
      long totalWrites;
      long loopOverhead, operationCost;

      totalWrites= ((long)data1)*1000L;
      sb.append( "  total writes="+totalWrites+" iteration count="+data2+" total time="+data3+" ms\r\n" );
      
      operationCost= (data3*1000000)/totalWrites;

      sb.append( "  instance variable write cost: "+ operationCost+" ns\r\n" );
      
      loopOverhead= pir.getLoopOverhead();
      if ( loopOverhead >= 0 )
      {
         operationCost= (data3*1000000-(((long)data1)*loopOverhead))/totalWrites;
         sb.append( "  instance variable write cost corrected for loop overhead: "+ operationCost+" ns\r\n" );         
      }
   }
}
