 // COPYRIGHT_BEGIN
 //  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 //  
 //  Copyright (C) 2008-2013, Cable Television Laboratories, Inc. 
 //  
 //  This software is available under multiple licenses: 
 //  
 //  (1) BSD 2-clause 
 //   Redistribution and use in source and binary forms, with or without modification, are
 //   permitted provided that the following conditions are met:
 //        ·Redistributions of source code must retain the above copyright notice, this list 
 //             of conditions and the following disclaimer.
 //        ·Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
 //             and the following disclaimer in the documentation and/or other materials provided with the 
 //             distribution.
 //   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 //   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
 //   TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
 //   PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 //   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 //   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 //   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 //   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
 //   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 //   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
 //   THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 //  
 //  (2) GPL Version 2
 //   This program is free software; you can redistribute it and/or modify
 //   it under the terms of the GNU General Public License as published by
 //   the Free Software Foundation, version 2. This program is distributed
 //   in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 //   even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 //   PURPOSE. See the GNU General Public License for more details.
 //  
 //   You should have received a copy of the GNU General Public License along
 //   with this program.If not, see<http:www.gnu.org/licenses/>.
 //  
 //  (3)CableLabs License
 //   If you or the company you represent has a separate agreement with CableLabs
 //   concerning the use of this code, your rights and obligations with respect
 //   to this code shall be as set forth therein. No license is granted hereunder
 //   for any other purpose.
 //  
 //   Please contact CableLabs if you need additional information or 
 //   have any questions.
 //  
 //       CableLabs
 //       858 Coal Creek Cir
 //       Louisville, CO 80027-9750
 //       303 661-9100
 // COPYRIGHT_END
 

package com.tvworks.plateval.fundamental;

import com.tvworks.plateval.TestCaseSet;
import com.tvworks.plateval.format.PlatformInformationRepository;
import com.tvworks.plateval.framework.TestCase;
import com.tvworks.plateval.util.ResultLog;

public class StaticVariableRead implements TestCase
{
   public static void touch()
   {      
   }
   
   public void run()
   {
      long runTime, totalRunTime;
      int count, totalCount, loopCount;
      
      loopCount= 0;
      totalCount= 0;
      totalRunTime= 0;
      count= 1000;
      for(;;)
      {
         ++loopCount;         
         runTime= doRun(count);
         totalRunTime += runTime;
         totalCount += count;
         count *= 2;
         if ( totalRunTime > 30000 )
         {
            break;
         }
         Thread.yield();
      }
      
      ResultLog.getInstance().add( TestCaseSet.TEST_StaticVariableRead, totalCount, loopCount, totalRunTime );
   }
   
   private static int mA0;
   private static int mA1;
   private static int mA2;
   private static int mA3;
   private static int mA4;
   private static int mA5;
   private static int mA6;
   private static int mA7;
   private static int mA8;
   private static int mA9;
   public long doRun(int count)
   {
      long startTime, endTime, runTime;

      int a, b, c, d, e, f, g, h, i, j, k;
      startTime= System.currentTimeMillis();
      while( count-- > 0 )
      {
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
         a= mA0;
         b= mA1;
         c= mA2;
         d= mA3;
         e= mA4;
         f= mA5;
         g= mA6;
         h= mA7;
         i= mA8;
         j= mA9;
         k= mA0;
         a= mA1;
         b= mA2;
         c= mA3;
         d= mA4;
         e= mA5;
         f= mA6;
         g= mA7;
         h= mA8;
         i= mA9;
         j= mA0;
         k= mA1;
         a= mA2;
         b= mA3;
         c= mA4;
         d= mA5;
         e= mA6;
         f= mA7;
         g= mA8;
         h= mA9;
         i= mA0;
         j= mA1;
         k= mA2;
         a= mA3;
         b= mA4;
         c= mA5;
         d= mA6;
         e= mA7;
         f= mA8;
         g= mA9;
         h= mA0;
         i= mA1;
         j= mA2;
         k= mA3;
         a= mA4;
         b= mA5;
         c= mA6;
         d= mA7;
         e= mA8;
         f= mA9;
         g= mA0;
         h= mA1;
         i= mA2;
         j= mA3;
         k= mA4;
         a= mA5;
         b= mA6;
         c= mA7;
         d= mA8;
         e= mA9;
         f= mA0;
         g= mA1;
         h= mA2;
         i= mA3;
         j= mA4;
         k= mA5;
         a= mA6;
         b= mA7;
         c= mA8;
         d= mA9;
         e= mA0;
         f= mA1;
         g= mA2;
         h= mA3;
         i= mA4;
         j= mA5;
         k= mA6;
         a= mA7;
         b= mA8;
         c= mA9;
         d= mA0;
         e= mA1;
         f= mA2;
         g= mA3;
         h= mA4;
         i= mA5;
         j= mA6;
         k= mA7;
         a= mA8;
         b= mA9;
         c= mA0;
         d= mA1;
         e= mA2;
         f= mA3;
         g= mA4;
         h= mA5;
         i= mA6;
         j= mA7;
         k= mA8;
         a= mA9;
      }
      endTime= System.currentTimeMillis();
      runTime= endTime-startTime;
      
      return runTime;
   }

   public static void format( PlatformInformationRepository pir, StringBuffer sb, int data1, int data2, long data3 )
   {
      long totalReads;
      long loopOverhead, operationCost, writeCost;
      
      totalReads= ((long)data1)*1000L;
      sb.append( "  total reads="+totalReads+" iteration count="+data2+" total time="+data3+" ms\r\n" );
      
      operationCost= (data3*1000000)/totalReads;

      sb.append( "  static variable read cost: "+ operationCost+" ns\r\n" );
      
      loopOverhead= pir.getLoopOverhead();
      if ( loopOverhead >= 0 )
      {
         operationCost= (data3*1000000-(((long)data1)*loopOverhead))/totalReads;
         sb.append( "  static variable read cost corrected for loop overhead: "+ operationCost+" ns\r\n" );         
      }
   }
}
