/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef HRDEVICETABLE_H
#define HRDEVICETABLE_H

/* function declarations */
void init_hrDeviceTable(void);
void initialize_table_hrDeviceTable(void);
Netsnmp_Node_Handler hrDeviceTable_handler;

/* column number definitions for table hrDeviceTable */
       #define COLUMN_HRDEVICEINDEX		1
       #define COLUMN_HRDEVICETYPE		2
       #define COLUMN_HRDEVICEDESCR		3
       #define COLUMN_HRDEVICEID		4
       #define COLUMN_HRDEVICESTATUS		5
       #define COLUMN_HRDEVICEERRORS		6
#endif /* HRDEVICETABLE_H */
