/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef HRPROCESSORTABLE_H
#define HRPROCESSORTABLE_H

/* function declarations */
void init_hrProcessorTable(void);
void initialize_table_hrProcessorTable(void);
Netsnmp_Node_Handler hrProcessorTable_handler;

/* column number definitions for table hrProcessorTable */
       #define COLUMN_HRPROCESSORFRWID		1
       #define COLUMN_HRPROCESSORLOAD		2
#endif /* HRPROCESSORTABLE_H */
