/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef HRSTORAGETABLE_H
#define HRSTORAGETABLE_H

/* function declarations */
void init_hrStorageTable(void);
void initialize_table_hrStorageTable(void);
Netsnmp_Node_Handler hrStorageTable_handler;

/* column number definitions for table hrStorageTable */
       #define COLUMN_HRSTORAGEINDEX		1
       #define COLUMN_HRSTORAGETYPE		2
       #define COLUMN_HRSTORAGEDESCR		3
       #define COLUMN_HRSTORAGEALLOCATIONUNITS		4
       #define COLUMN_HRSTORAGESIZE		5
       #define COLUMN_HRSTORAGEUSED		6
       #define COLUMN_HRSTORAGEALLOCATIONFAILURES		7
#endif /* HRSTORAGETABLE_H */
