/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ifTable.h"

/** Initialize the ifTable table by defining its contents and how it's structured */
void
initialize_table_ifTable(void)
{
    static oid ifTable_oid[] = {1,3,6,1,2,1,2,2};
    size_t ifTable_oid_len = OID_LENGTH(ifTable_oid);
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ifTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ifTable",
                "adding indexes to table ifTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: ifIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ifTable",
                "adding column types to table ifTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_IFINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFDESCR, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_IFTYPE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFMTU, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFSPEED, ASN_GAUGE, 0,
                                            NULL, 0,
                                            COLUMN_IFPHYSADDRESS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_IFADMINSTATUS, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_IFOPERSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFLASTCHANGE, ASN_TIMETICKS, 0,
                                            NULL, 0,
                                            COLUMN_IFINOCTETS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINNUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINDISCARDS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINUNKNOWNPROTOS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTOCTETS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTNUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTDISCARDS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTQLEN, ASN_GAUGE, 0,
                                            NULL, 0,
                                            COLUMN_IFSPECIFIC, ASN_OBJECT_ID, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ifTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ifTable", ifTable_handler,
                                                        ifTable_oid,
                                                        ifTable_oid_len,
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ifTable module */
void
init_ifTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ifTable();
}

/** handles requests for the ifTable table, if anything else needs to be done */
int
ifTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
