/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCHNNETCONFIG_H
#define OCHNNETCONFIG_H

/* function declarations */
void init_ocHnNetConfig(void);
Netsnmp_Node_Handler handle_ocHnNetConfigViewPrimaryOutputPort;
Netsnmp_Node_Handler handle_ocHnNetConfigViewPrimaryOutputPortOrgID;
Netsnmp_Node_Handler handle_ocHnNetConfigPersistentLinkLocalAddress;

#endif /* OCHNNETCONFIG_H */
