/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSYSTEMDRIVEINFOTABLE_H
#define OCSTBHOSTSYSTEMDRIVEINFOTABLE_H

/* function declarations */
void init_ocStbHostSystemDriveInfoTable(void);
void initialize_table_ocStbHostSystemDriveInfoTable(void);
Netsnmp_Node_Handler ocStbHostSystemDriveInfoTable_handler;

/* column number definitions for table ocStbHostSystemDriveInfoTable */
       #define COLUMN_OCSTBHOSTSYSTEMDRIVEINFOINDEX		1
       #define COLUMN_OCSTBHOSTSYSTEMDRIVEINFOVENDORID		2
       #define COLUMN_OCSTBHOSTSYSTEMDRIVEINFOPRODUCTID		3
       #define COLUMN_OCSTBHOSTSYSTEMDRIVEINFOSERIALNUMBER		4
       #define COLUMN_OCSTBHOSTSYSTEMDRIVEINFOINTERFACETYPE		5
#endif /* OCSTBHOSTSYSTEMDRIVEINFOTABLE_H */
