/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSPDIFTABLE_H
#define OCSTBHOSTSPDIFTABLE_H

/* function declarations */
void init_ocStbHostSPDIfTable(void);
void initialize_table_ocStbHostSPDIfTable(void);
Netsnmp_Node_Handler ocStbHostSPDIfTable_handler;

/* column number definitions for table ocStbHostSPDIfTable */
       #define COLUMN_OCSTBHOSTSPDIFAUDIOFORMAT		1
       #define COLUMN_OCSTBHOSTSPDIFAUDIOMUTESTATUS		2
#endif /* OCSTBHOSTSPDIFTABLE_H */
