/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTCARDCPINFO_H
#define OCSTBHOSTCARDCPINFO_H

/* function declarations */
void init_ocStbHostCardCpInfo(void);
Netsnmp_Node_Handler handle_ocStbHostCardCpAuthKeyStatus;
Netsnmp_Node_Handler handle_ocStbHostCardCpCertificateCheck;
Netsnmp_Node_Handler handle_ocStbHostCardCpCciChallengeCount;
Netsnmp_Node_Handler handle_ocStbHostCardCpKeyGenerationReqCount;
Netsnmp_Node_Handler handle_ocStbHostCardCpIdList;

#endif /* OCSTBHOSTCARDCPINFO_H */
