/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTCOMPONENTVIDEOTABLE_H
#define OCSTBHOSTCOMPONENTVIDEOTABLE_H

/* function declarations */
void init_ocStbHostComponentVideoTable(void);
void initialize_table_ocStbHostComponentVideoTable(void);
Netsnmp_Node_Handler ocStbHostComponentVideoTable_handler;

/* column number definitions for table ocStbHostComponentVideoTable */
       #define COLUMN_OCSTBHOSTCOMPONENTVIDEOCONSTRAINEDSTATUS		1
       #define COLUMN_OCSTBHOSTCOMPONENTOUTPUTFORMAT		2
       #define COLUMN_OCSTBHOSTCOMPONENTASPECTRATIO		3
       #define COLUMN_OCSTBHOSTCOMPONENTVIDEOMUTESTATUS		4
#endif /* OCSTBHOSTCOMPONENTVIDEOTABLE_H */
