/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTRFCHANNELOUTTABLE_H
#define OCSTBHOSTRFCHANNELOUTTABLE_H

/* function declarations */
void init_ocStbHostRFChannelOutTable(void);
void initialize_table_ocStbHostRFChannelOutTable(void);
Netsnmp_Node_Handler ocStbHostRFChannelOutTable_handler;

/* column number definitions for table ocStbHostRFChannelOutTable */
       #define COLUMN_OCSTBHOSTRFCHANNELOUT		2
       #define COLUMN_OCSTBHOSTRFCHANNELOUTAUDIOMUTESTATUS		3
       #define COLUMN_OCSTBHOSTRFCHANNELOUTVIDEOMUTESTATUS		4
#endif /* OCSTBHOSTRFCHANNELOUTTABLE_H */
