/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTPROGRAMSTATUSTABLE_H
#define OCSTBHOSTPROGRAMSTATUSTABLE_H

/* function declarations */
void init_ocStbHostProgramStatusTable(void);
void initialize_table_ocStbHostProgramStatusTable(void);
Netsnmp_Node_Handler ocStbHostProgramStatusTable_handler;

/* column number definitions for table ocStbHostProgramStatusTable */
       #define COLUMN_OCSTBHOSTPROGRAMINDEX		1
       #define COLUMN_OCSTBHOSTPROGRAMAVSOURCE		2
       #define COLUMN_OCSTBHOSTPROGRAMAVDESTINATION		3
       #define COLUMN_OCSTBHOSTPROGRAMCONTENTSOURCE		4
       #define COLUMN_OCSTBHOSTPROGRAMCONTENTDESTINATION		5
#endif /* OCSTBHOSTPROGRAMSTATUSTABLE_H */
