/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTFIRMWAREDOWNLOADSTATUS_H
#define OCSTBHOSTFIRMWAREDOWNLOADSTATUS_H

/* function declarations */
void init_ocStbHostFirmwareDownloadStatus(void);
Netsnmp_Node_Handler handle_ocStbHostFirmwareImageStatus;
Netsnmp_Node_Handler handle_ocStbHostFirmwareCodeDownloadStatus;
Netsnmp_Node_Handler handle_ocStbHostFirmwareCodeObjectName;
Netsnmp_Node_Handler handle_ocStbHostFirmwareDownloadFailedStatus;
Netsnmp_Node_Handler handle_ocStbHostFirmwareDownloadFailedCount;
Netsnmp_Node_Handler handle_ocStbHostFirmwareDownloadGroupId;

#endif /* OCSTBHOSTFIRMWAREDOWNLOADSTATUS_H */
