/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostMpeg2ContentTable.h"

/** Initialize the ocStbHostMpeg2ContentTable table by defining its contents and how it's structured */
void
initialize_table_ocStbHostMpeg2ContentTable(void)
{
    static oid ocStbHostMpeg2ContentTable_oid[] = {1,3,6,1,4,1,4491,2,3,1,1,1,2,7,3};
    size_t ocStbHostMpeg2ContentTable_oid_len = OID_LENGTH(ocStbHostMpeg2ContentTable_oid);
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ocStbHostMpeg2ContentTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ocStbHostMpeg2ContentTable",
                "adding indexes to table ocStbHostMpeg2ContentTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_UNSIGNED,  /* index: ocStbHostMpeg2ContentIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ocStbHostMpeg2ContentTable",
                "adding column types to table ocStbHostMpeg2ContentTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTINDEX, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTPROGRAMNUMBER, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTTRANSPORTSTREAMID, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTTOTALSTREAMS, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTSELECTEDVIDEOPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTSELECTEDAUDIOPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTOTHERAUDIOPIDS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTCCIVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTAPSVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTCITSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTBROADCASTFLAGSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTEPNSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTPCRPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTPCRLOCKSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTDECODERPTS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTDISCONTINUITIES, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTPKTERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTPIPELINEERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTENTDECODERRESTARTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG2CONTAINERFORMAT, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ocStbHostMpeg2ContentTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ocStbHostMpeg2ContentTable", ocStbHostMpeg2ContentTable_handler,
                                                        ocStbHostMpeg2ContentTable_oid,
                                                        ocStbHostMpeg2ContentTable_oid_len,
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ocStbHostMpeg2ContentTable module */
void
init_ocStbHostMpeg2ContentTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ocStbHostMpeg2ContentTable();
}

/** handles requests for the ocStbHostMpeg2ContentTable table, if anything else needs to be done */
int
ocStbHostMpeg2ContentTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
