/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSOFTWAREAPPLICATIONINFOTABLE_H
#define OCSTBHOSTSOFTWAREAPPLICATIONINFOTABLE_H

/* function declarations */
void init_ocStbHostSoftwareApplicationInfoTable(void);
void initialize_table_ocStbHostSoftwareApplicationInfoTable(void);
Netsnmp_Node_Handler ocStbHostSoftwareApplicationInfoTable_handler;

/* column number definitions for table ocStbHostSoftwareApplicationInfoTable */
       #define COLUMN_OCSTBHOSTSOFTWAREAPPNAMESTRING		1
       #define COLUMN_OCSTBHOSTSOFTWAREAPPVERSIONNUMBER		2
       #define COLUMN_OCSTBHOSTSOFTWARESTATUS		3
       #define COLUMN_OCSTBHOSTSOFTWAREAPPLICATIONINFOINDEX		4
       #define COLUMN_OCSTBHOSTSOFTWAREORGANIZATIONID		5
       #define COLUMN_OCSTBHOSTSOFTWAREAPPLICATIONID		6
       #define COLUMN_OCSTBHOSTSOFTWAREAPPLICATIONSIGSTATUS		7
       #define COLUMN_OCSTBHOSTSOFTWAREAPPLICATIONPRIORITY		8
#endif /* OCSTBHOSTSOFTWAREAPPLICATIONINFOTABLE_H */
