/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostDVIHDMITable.h"

/** Initialize the ocStbHostDVIHDMITable table by defining its contents and how it's structured */
void
initialize_table_ocStbHostDVIHDMITable(void)
{
    static oid ocStbHostDVIHDMITable_oid[] = {1,3,6,1,4,1,4491,2,3,1,1,1,2,4,1};
    size_t ocStbHostDVIHDMITable_oid_len = OID_LENGTH(ocStbHostDVIHDMITable_oid);
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ocStbHostDVIHDMITable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ocStbHostDVIHDMITable",
                "adding indexes to table ocStbHostDVIHDMITable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_UNSIGNED,  /* index: ocStbHostAVInterfaceIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ocStbHostDVIHDMITable",
                "adding column types to table ocStbHostDVIHDMITable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_OCSTBHOSTDVIHDMIOUTPUTTYPE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMICONNECTIONSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIREPEATERSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIVIDEOXMISSIONSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIHDCPSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIVIDEOMUTESTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIOUTPUTFORMAT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIASPECTRATIO, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIHOSTDEVICEHDCPSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIAUDIOFORMAT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIAUDIOSAMPLERATE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIAUDIOCHANNELCOUNT, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIAUDIOMUTESTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIAUDIOSAMPLESIZE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMICOLORSPACE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIFRAMERATE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIATTACHEDDEVICETYPE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIEDID, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMILIPSYNCDELAY, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMICECFEATURES, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIFEATURES, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIMAXDEVICECOUNT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIPREFERREDVIDEOFORMAT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMIEDIDVERSION, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMI3DCOMPATIBILITYCONTROL, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTDVIHDMI3DCOMPATIBILITYMSGDISPLAY, ASN_INTEGER, 1,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ocStbHostDVIHDMITable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ocStbHostDVIHDMITable", ocStbHostDVIHDMITable_handler,
                                                        ocStbHostDVIHDMITable_oid,
                                                        ocStbHostDVIHDMITable_oid_len,
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ocStbHostDVIHDMITable module */
void
init_ocStbHostDVIHDMITable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ocStbHostDVIHDMITable();
}

/** handles requests for the ocStbHostDVIHDMITable table, if anything else needs to be done */
int
ocStbHostDVIHDMITable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
