/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTDEVICESOFTWAREBASE_H
#define OCSTBHOSTDEVICESOFTWAREBASE_H

/* function declarations */
void init_ocStbHostDeviceSoftwareBase(void);
Netsnmp_Node_Handler handle_ocStbHostSoftwareFirmwareVersion;
Netsnmp_Node_Handler handle_ocStbHostSoftwareOCAPVersion;
Netsnmp_Node_Handler handle_ocStbHostSoftwareFirmwareReleaseDate;
Netsnmp_Node_Handler handle_ocStbHostSoftwareBootloaderVersion;

#endif /* OCSTBHOSTDEVICESOFTWAREBASE_H */
