/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSYSTEMHOMENETWORKTABLE_H
#define OCSTBHOSTSYSTEMHOMENETWORKTABLE_H

/* function declarations */
void init_ocStbHostSystemHomeNetworkTable(void);
void initialize_table_ocStbHostSystemHomeNetworkTable(void);
Netsnmp_Node_Handler ocStbHostSystemHomeNetworkTable_handler;

/* column number definitions for table ocStbHostSystemHomeNetworkTable */
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKINDEX		1
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKMAXCLIENTS		2
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKHOSTDRMSTATUS		3
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCONNECTEDCLIENTS		4
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCLIENTMACADDRESS		5
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCLIENTIPADDRESS		6
       #define COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCLIENTDRMSTATUS		7
#endif /* OCSTBHOSTSYSTEMHOMENETWORKTABLE_H */
