/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostEasObjects.h"

/** Initializes the ocStbHostEasObjects module */
void
init_ocStbHostEasObjects(void)
{
    static oid ocStbEasMessageStateCode_oid[] = { 1,3,6,1,4,1,4491,2,3,1,1,1,3,1,1 };
    static oid ocStbEasMessageCountyCode_oid[] = { 1,3,6,1,4,1,4491,2,3,1,1,1,3,1,2 };
    static oid ocStbEasMessageCountySubdivisionCode_oid[] = { 1,3,6,1,4,1,4491,2,3,1,1,1,3,1,3 };

  DEBUGMSGTL(("ocStbHostEasObjects", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ocStbEasMessageStateCode", handle_ocStbEasMessageStateCode,
                               ocStbEasMessageStateCode_oid, OID_LENGTH(ocStbEasMessageStateCode_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ocStbEasMessageCountyCode", handle_ocStbEasMessageCountyCode,
                               ocStbEasMessageCountyCode_oid, OID_LENGTH(ocStbEasMessageCountyCode_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ocStbEasMessageCountySubdivisionCode", handle_ocStbEasMessageCountySubdivisionCode,
                               ocStbEasMessageCountySubdivisionCode_oid, OID_LENGTH(ocStbEasMessageCountySubdivisionCode_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_ocStbEasMessageStateCode(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_UNSIGNED,
                                     (u_char *) /* XXX: a pointer to the scalar's data */,
                                     /* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ocStbEasMessageStateCode\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_ocStbEasMessageCountyCode(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_UNSIGNED,
                                     (u_char *) /* XXX: a pointer to the scalar's data */,
                                     /* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ocStbEasMessageCountyCode\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_ocStbEasMessageCountySubdivisionCode(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_UNSIGNED,
                                     (u_char *) /* XXX: a pointer to the scalar's data */,
                                     /* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ocStbEasMessageCountySubdivisionCode\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
