/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostMpeg4ContentTable.h"

/** Initialize the ocStbHostMpeg4ContentTable table by defining its contents and how it's structured */
void
initialize_table_ocStbHostMpeg4ContentTable(void)
{
    static oid ocStbHostMpeg4ContentTable_oid[] = {1,3,6,1,4,1,4491,2,3,1,1,1,2,7,5};
    size_t ocStbHostMpeg4ContentTable_oid_len = OID_LENGTH(ocStbHostMpeg4ContentTable_oid);
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ocStbHostMpeg4ContentTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ocStbHostMpeg4ContentTable",
                "adding indexes to table ocStbHostMpeg4ContentTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_UNSIGNED,  /* index: ocStbHostMpeg4ContentIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ocStbHostMpeg4ContentTable",
                "adding column types to table ocStbHostMpeg4ContentTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTINDEX, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTPROGRAMNUMBER, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTTRANSPORTSTREAMID, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTTOTALSTREAMS, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTSELECTEDVIDEOPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTSELECTEDAUDIOPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTOTHERAUDIOPIDS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTCCIVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTAPSVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTCITSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTBROADCASTFLAGSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTEPNSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTPCRPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTPCRLOCKSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTDECODERPTS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTDISCONTINUITIES, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTPKTERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTPIPELINEERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTENTDECODERRESTARTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTMPEG4CONTAINERFORMAT, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ocStbHostMpeg4ContentTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ocStbHostMpeg4ContentTable", ocStbHostMpeg4ContentTable_handler,
                                                        ocStbHostMpeg4ContentTable_oid,
                                                        ocStbHostMpeg4ContentTable_oid_len,
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ocStbHostMpeg4ContentTable module */
void
init_ocStbHostMpeg4ContentTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ocStbHostMpeg4ContentTable();
}

/** handles requests for the ocStbHostMpeg4ContentTable table, if anything else needs to be done */
int
ocStbHostMpeg4ContentTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
