/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTQPSKOBJECTS_H
#define OCSTBHOSTQPSKOBJECTS_H

/* function declarations */
void init_ocStbHostQpskObjects(void);
Netsnmp_Node_Handler handle_ocStbHostQpskFDCFreq;
Netsnmp_Node_Handler handle_ocStbHostQpskRDCFreq;
Netsnmp_Node_Handler handle_ocStbHostQpskFDCBer;
Netsnmp_Node_Handler handle_ocStbHostQpskFDCStatus;
Netsnmp_Node_Handler handle_ocStbHostQpskFDCBytesRead;
Netsnmp_Node_Handler handle_ocStbHostQpskFDCPower;
Netsnmp_Node_Handler handle_ocStbHostQpskFDCLockedTime;
Netsnmp_Node_Handler handle_ocStbHostQpskFDCSNR;
Netsnmp_Node_Handler handle_ocStbHostQpskAGC;
Netsnmp_Node_Handler handle_ocStbHostQpskRDCPower;
Netsnmp_Node_Handler handle_ocStbHostQpskRDCDataRate;

#endif /* OCSTBHOSTQPSKOBJECTS_H */
