/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostIEEE1394Table.h"

/** Initialize the ocStbHostIEEE1394Table table by defining its contents and how it's structured */
void
initialize_table_ocStbHostIEEE1394Table(void)
{
    static oid ocStbHostIEEE1394Table_oid[] = {1,3,6,1,4,1,4491,2,3,1,1,1,2,3,1};
    size_t ocStbHostIEEE1394Table_oid_len = OID_LENGTH(ocStbHostIEEE1394Table_oid);
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ocStbHostIEEE1394Table");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ocStbHostIEEE1394Table",
                "adding indexes to table ocStbHostIEEE1394Table\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_UNSIGNED,  /* index: ocStbHostAVInterfaceIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ocStbHostIEEE1394Table",
                "adding column types to table ocStbHostIEEE1394Table\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_OCSTBHOSTIEEE1394ACTIVENODES, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394DATAXMISSION, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394DTCPSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394LOOPSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394ROOTSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394CYCLEISMASTER, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394IRMSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394AUDIOMUTESTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTIEEE1394VIDEOMUTESTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ocStbHostIEEE1394Table_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ocStbHostIEEE1394Table", ocStbHostIEEE1394Table_handler,
                                                        ocStbHostIEEE1394Table_oid,
                                                        ocStbHostIEEE1394Table_oid_len,
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ocStbHostIEEE1394Table module */
void
init_ocStbHostIEEE1394Table(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ocStbHostIEEE1394Table();
}

/** handles requests for the ocStbHostIEEE1394Table table, if anything else needs to be done */
int
ocStbHostIEEE1394Table_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
