/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTIEEE1394TABLE_H
#define OCSTBHOSTIEEE1394TABLE_H

/* function declarations */
void init_ocStbHostIEEE1394Table(void);
void initialize_table_ocStbHostIEEE1394Table(void);
Netsnmp_Node_Handler ocStbHostIEEE1394Table_handler;

/* column number definitions for table ocStbHostIEEE1394Table */
       #define COLUMN_OCSTBHOSTIEEE1394ACTIVENODES		1
       #define COLUMN_OCSTBHOSTIEEE1394DATAXMISSION		2
       #define COLUMN_OCSTBHOSTIEEE1394DTCPSTATUS		3
       #define COLUMN_OCSTBHOSTIEEE1394LOOPSTATUS		4
       #define COLUMN_OCSTBHOSTIEEE1394ROOTSTATUS		5
       #define COLUMN_OCSTBHOSTIEEE1394CYCLEISMASTER		6
       #define COLUMN_OCSTBHOSTIEEE1394IRMSTATUS		7
       #define COLUMN_OCSTBHOSTIEEE1394AUDIOMUTESTATUS		8
       #define COLUMN_OCSTBHOSTIEEE1394VIDEOMUTESTATUS		9
#endif /* OCSTBHOSTIEEE1394TABLE_H */
