/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTAVINTERFACETABLE_H
#define OCSTBHOSTAVINTERFACETABLE_H

/* function declarations */
void init_ocStbHostAVInterfaceTable(void);
void initialize_table_ocStbHostAVInterfaceTable(void);
Netsnmp_Node_Handler ocStbHostAVInterfaceTable_handler;

/* column number definitions for table ocStbHostAVInterfaceTable */
       #define COLUMN_OCSTBHOSTAVINTERFACEINDEX		1
       #define COLUMN_OCSTBHOSTAVINTERFACETYPE		2
       #define COLUMN_OCSTBHOSTAVINTERFACEDESC		3
       #define COLUMN_OCSTBHOSTAVINTERFACESTATUS		4
#endif /* OCSTBHOSTAVINTERFACETABLE_H */
