/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTIEEE1394CONNECTEDDEVICESTABLE_H
#define OCSTBHOSTIEEE1394CONNECTEDDEVICESTABLE_H

/* function declarations */
void init_ocStbHostIEEE1394ConnectedDevicesTable(void);
void initialize_table_ocStbHostIEEE1394ConnectedDevicesTable(void);
Netsnmp_Node_Handler ocStbHostIEEE1394ConnectedDevicesTable_handler;

/* column number definitions for table ocStbHostIEEE1394ConnectedDevicesTable */
       #define COLUMN_OCSTBHOSTIEEE1394CONNECTEDDEVICESINDEX		1
       #define COLUMN_OCSTBHOSTIEEE1394CONNECTEDDEVICESAVINTERFACEINDEX		2
       #define COLUMN_OCSTBHOSTIEEE1394CONNECTEDDEVICESSUBUNITTYPE		3
       #define COLUMN_OCSTBHOSTIEEE1394CONNECTEDDEVICESEUI64		4
       #define COLUMN_OCSTBHOSTIEEE1394CONNECTEDDEVICESADSOURCESELECTSUPPORT		5
#endif /* OCSTBHOSTIEEE1394CONNECTEDDEVICESTABLE_H */
