/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTSYSTEMLOGGINGEVENTENTRY_H
#define OCSTBHOSTSYSTEMLOGGINGEVENTENTRY_H

/* function declarations */
void init_ocStbHostSystemLoggingEventEntry(void);
Netsnmp_Node_Handler handle_ocStbHostSystemLoggingEventIndex;
Netsnmp_Node_Handler handle_ocStbHostSystemLoggingEventTimeStamp;
Netsnmp_Node_Handler handle_ocStbHostSystemLoggingEventMessage;

#endif /* OCSTBHOSTSYSTEMLOGGINGEVENTENTRY_H */
