/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTHWIDENTIFIERS_H
#define OCSTBHOSTHWIDENTIFIERS_H

/* function declarations */
void init_ocStbHostHWIdentifiers(void);
Netsnmp_Node_Handler handle_ocStbHostSerialNumber;
Netsnmp_Node_Handler handle_ocStbHostHostID;
Netsnmp_Node_Handler handle_ocStbHostCapabilities;
Netsnmp_Node_Handler handle_ocStbHostAvcSupport;

#endif /* OCSTBHOSTHWIDENTIFIERS_H */
