/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTMEMORYINFO_H
#define OCSTBHOSTMEMORYINFO_H

/* function declarations */
void init_ocStbHostMemoryInfo(void);
Netsnmp_Node_Handler handle_ocStbHostLargestAvailableBlock;
Netsnmp_Node_Handler handle_ocStbHostTotalVideoMemory;
Netsnmp_Node_Handler handle_ocStbHostAvailableVideoMemory;
Netsnmp_Node_Handler handle_ocStbHostTotalSystemMemory;
Netsnmp_Node_Handler handle_ocStbHostAvailableSystemMemory;

#endif /* OCSTBHOSTMEMORYINFO_H */
