/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostCCMMI.h"

/** Initializes the ocStbHostCCMMI module */
void
init_ocStbHostCCMMI(void)
{

  DEBUGMSGTL(("ocStbHostCCMMI", "Initializing\n"));

}

