/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTSECURITYSUBSYSTEM_H
#define OCSTBHOSTSECURITYSUBSYSTEM_H

/* function declarations */
void init_ocStbHostSecuritySubSystem(void);
Netsnmp_Node_Handler handle_ocStbHostSecurityIdentifier;
Netsnmp_Node_Handler handle_ocStbHostCASystemIdentifier;
Netsnmp_Node_Handler handle_ocStbHostCAType;

#endif /* OCSTBHOSTSECURITYSUBSYSTEM_H */
