/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSYSTEMMEMORYREPORTTABLE_H
#define OCSTBHOSTSYSTEMMEMORYREPORTTABLE_H

/* function declarations */
void init_ocStbHostSystemMemoryReportTable(void);
void initialize_table_ocStbHostSystemMemoryReportTable(void);
Netsnmp_Node_Handler ocStbHostSystemMemoryReportTable_handler;

/* column number definitions for table ocStbHostSystemMemoryReportTable */
       #define COLUMN_OCSTBHOSTSYSTEMMEMORYREPORTINDEX		1
       #define COLUMN_OCSTBHOSTSYSTEMMEMORYREPORTMEMORYTYPE		2
       #define COLUMN_OCSTBHOSTSYSTEMMEMORYREPORTMEMORYSIZE		3
#endif /* OCSTBHOSTSYSTEMMEMORYREPORTTABLE_H */
