/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTSNMPPROXYINFO_H
#define OCSTBHOSTSNMPPROXYINFO_H

/* function declarations */
void init_ocStbHostSnmpProxyInfo(void);
Netsnmp_Node_Handler handle_ocStbHostCardMfgId;
Netsnmp_Node_Handler handle_ocStbHostCardVersion;
Netsnmp_Node_Handler handle_ocStbHostCardRootOid;
Netsnmp_Node_Handler handle_ocStbHostCardSerialNumber;
Netsnmp_Node_Handler handle_ocStbHostCardSnmpAccessControl;

#endif /* OCSTBHOSTSNMPPROXYINFO_H */
