/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ocStbHostSystemHomeNetworkTable.h"

/** Initialize the ocStbHostSystemHomeNetworkTable table by defining its contents and how it's structured */
void
initialize_table_ocStbHostSystemHomeNetworkTable(void)
{
    static oid ocStbHostSystemHomeNetworkTable_oid[] = {1,3,6,1,4,1,4491,2,3,1,1,4,3,2};
    size_t ocStbHostSystemHomeNetworkTable_oid_len = OID_LENGTH(ocStbHostSystemHomeNetworkTable_oid);
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ocStbHostSystemHomeNetworkTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ocStbHostSystemHomeNetworkTable",
                "adding indexes to table ocStbHostSystemHomeNetworkTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_UNSIGNED,  /* index: ocStbHostSystemHomeNetworkIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ocStbHostSystemHomeNetworkTable",
                "adding column types to table ocStbHostSystemHomeNetworkTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKINDEX, ASN_UNSIGNED, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKMAXCLIENTS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKHOSTDRMSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCONNECTEDCLIENTS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCLIENTMACADDRESS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCLIENTIPADDRESS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_OCSTBHOSTSYSTEMHOMENETWORKCLIENTDRMSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ocStbHostSystemHomeNetworkTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ocStbHostSystemHomeNetworkTable", ocStbHostSystemHomeNetworkTable_handler,
                                                        ocStbHostSystemHomeNetworkTable_oid,
                                                        ocStbHostSystemHomeNetworkTable_oid_len,
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ocStbHostSystemHomeNetworkTable module */
void
init_ocStbHostSystemHomeNetworkTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ocStbHostSystemHomeNetworkTable();
}

/** handles requests for the ocStbHostSystemHomeNetworkTable table, if anything else needs to be done */
int
ocStbHostSystemHomeNetworkTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
