/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSYSTEMTEMPTABLE_H
#define OCSTBHOSTSYSTEMTEMPTABLE_H

/* function declarations */
void init_ocStbHostSystemTempTable(void);
void initialize_table_ocStbHostSystemTempTable(void);
Netsnmp_Node_Handler ocStbHostSystemTempTable_handler;

/* column number definitions for table ocStbHostSystemTempTable */
       #define COLUMN_OCSTBHOSTSYSTEMTEMPINDEX		1
       #define COLUMN_OCSTBHOSTSYSTEMTEMPDESCR		2
       #define COLUMN_OCSTBHOSTSYSTEMTEMPVALUE		3
       #define COLUMN_OCSTBHOSTSYSTEMTEMPLASTUPDATE		4
       #define COLUMN_OCSTBHOSTSYSTEMTEMPMAXVALUE		5
#endif /* OCSTBHOSTSYSTEMTEMPTABLE_H */
