/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTANALOGVIDEOTABLE_H
#define OCSTBHOSTANALOGVIDEOTABLE_H

/* function declarations */
void init_ocStbHostAnalogVideoTable(void);
void initialize_table_ocStbHostAnalogVideoTable(void);
Netsnmp_Node_Handler ocStbHostAnalogVideoTable_handler;

/* column number definitions for table ocStbHostAnalogVideoTable */
       #define COLUMN_OCSTBHOSTANALOGVIDEOPROTECTIONSTATUS		1
#endif /* OCSTBHOSTANALOGVIDEOTABLE_H */
