/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTREBOOTINFO_H
#define OCSTBHOSTREBOOTINFO_H

/* function declarations */
void init_ocStbHostRebootInfo(void);
Netsnmp_Node_Handler handle_ocStbHostRebootType;
Netsnmp_Node_Handler handle_ocStbHostRebootReset;

#endif /* OCSTBHOSTREBOOTINFO_H */
