/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTDUMPTRAPINFO_H
#define OCSTBHOSTDUMPTRAPINFO_H

/* function declarations */
void init_ocStbHostDumpTrapInfo(void);
Netsnmp_Node_Handler handle_ocStbHostDumpEventCount;
Netsnmp_Node_Handler handle_ocStbHostDumpNow;
Netsnmp_Node_Handler handle_ocStbHostDumpEventTimeout;
Netsnmp_Node_Handler handle_ocStbHostDumpFilePath;

#endif /* OCSTBHOSTDUMPTRAPINFO_H */
