/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTSYSTEMLOGGING_H
#define OCSTBHOSTSYSTEMLOGGING_H

/* function declarations */
void init_ocStbHostSystemLogging(void);
Netsnmp_Node_Handler handle_ocStbHostSystemLoggingControlReset;
Netsnmp_Node_Handler handle_ocStbHostSystemLoggingSize;
Netsnmp_Node_Handler handle_ocStbHostSystemLoggingLevelControl;
Netsnmp_Node_Handler handle_ocStbHostSystemloggingGroupControl;

#endif /* OCSTBHOSTSYSTEMLOGGING_H */
