/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTDVIHDMIAVAILABLEVIDEOFORMATTABLE_H
#define OCSTBHOSTDVIHDMIAVAILABLEVIDEOFORMATTABLE_H

/* function declarations */
void init_ocStbHostDVIHDMIAvailableVideoFormatTable(void);
void initialize_table_ocStbHostDVIHDMIAvailableVideoFormatTable(void);
Netsnmp_Node_Handler ocStbHostDVIHDMIAvailableVideoFormatTable_handler;

/* column number definitions for table ocStbHostDVIHDMIAvailableVideoFormatTable */
       #define COLUMN_OCSTBHOSTDVIHDMIAVAILABLEVIDEOFORMATINDEX		1
       #define COLUMN_OCSTBHOSTDVIHDMIAVAILABLEVIDEOFORMAT		2
       #define COLUMN_OCSTBHOSTDVIHDMISUPPORTED3DSTRUCTURES		3
       #define COLUMN_OCSTBHOSTDVIHDMIACTIVE3DSTRUCTURE		4
#endif /* OCSTBHOSTDVIHDMIAVAILABLEVIDEOFORMATTABLE_H */
