/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTINFO_H
#define OCSTBHOSTINFO_H

/* function declarations */
void init_ocStbHostInfo(void);
Netsnmp_Node_Handler handle_ocStbHostIpAddressType;
Netsnmp_Node_Handler handle_ocStbHostIpSubNetMask;
Netsnmp_Node_Handler handle_ocStbHostOobMessageMode;
Netsnmp_Node_Handler handle_ocStbHostDumpEventCount;
Netsnmp_Node_Handler handle_ocStbHostDumpNow;
Netsnmp_Node_Handler handle_ocStbHostDumpEventTimeout;
Netsnmp_Node_Handler handle_ocStbHostDumpFilePath;
Netsnmp_Node_Handler handle_ocStbHostCfrSpecificationIssue;
Netsnmp_Node_Handler handle_ocStbHostMibSpecificationIssue;
Netsnmp_Node_Handler handle_ocStbHostBootStatus;
Netsnmp_Node_Handler handle_ocStbHostPatTimeoutCount;
Netsnmp_Node_Handler handle_ocStbHostPmtTimeoutCount;
Netsnmp_Node_Handler handle_ocStbHostOobCarouselTimeoutCount;
Netsnmp_Node_Handler handle_ocStbHostInbandCarouselTimeoutCount;

#endif /* OCSTBHOSTINFO_H */
