/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTEASOBJECTS_H
#define OCSTBHOSTEASOBJECTS_H

/* function declarations */
void init_ocStbHostEasObjects(void);
Netsnmp_Node_Handler handle_ocStbEasMessageStateCode;
Netsnmp_Node_Handler handle_ocStbEasMessageCountyCode;
Netsnmp_Node_Handler handle_ocStbEasMessageCountySubdivisionCode;

#endif /* OCSTBHOSTEASOBJECTS_H */
