/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTVC1CONTENTTABLE_H
#define OCSTBHOSTVC1CONTENTTABLE_H

/* function declarations */
void init_ocStbHostVc1ContentTable(void);
void initialize_table_ocStbHostVc1ContentTable(void);
Netsnmp_Node_Handler ocStbHostVc1ContentTable_handler;

/* column number definitions for table ocStbHostVc1ContentTable */
       #define COLUMN_OCSTBHOSTVC1CONTENTINDEX		1
       #define COLUMN_OCSTBHOSTVC1CONTENTPROGRAMNUMBER		2
       #define COLUMN_OCSTBHOSTVC1CONTAINERFORMAT		20
#endif /* OCSTBHOSTVC1CONTENTTABLE_H */
