/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef OCSTBHOSTCONTENTERRORSUMMARYINFO_H
#define OCSTBHOSTCONTENTERRORSUMMARYINFO_H

/* function declarations */
void init_ocStbHostContentErrorSummaryInfo(void);
Netsnmp_Node_Handler handle_ocStbHostPatTimeoutCount;
Netsnmp_Node_Handler handle_ocStbHostPmtTimeoutCount;
Netsnmp_Node_Handler handle_ocStbHostOobCarouselTimeoutCount;
Netsnmp_Node_Handler handle_ocStbHostInbandCarouselTimeoutCount;

#endif /* OCSTBHOSTCONTENTERRORSUMMARYINFO_H */
