/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef OCSTBHOSTSYSTEMLOGGINGEVENTTABLE_H
#define OCSTBHOSTSYSTEMLOGGINGEVENTTABLE_H

/* function declarations */
void init_ocStbHostSystemLoggingEventTable(void);
void initialize_table_ocStbHostSystemLoggingEventTable(void);
Netsnmp_Node_Handler ocStbHostSystemLoggingEventTable_handler;

/* column number definitions for table ocStbHostSystemLoggingEventTable */
       #define COLUMN_OCSTBHOSTSYSTEMLOGGINGEVENTINDEX		1
       #define COLUMN_OCSTBHOSTSYSTEMLOGGINGEVENTTIMESTAMP		2
       #define COLUMN_OCSTBHOSTSYSTEMLOGGINGEVENTMESSAGE		3
#endif /* OCSTBHOSTSYSTEMLOGGINGEVENTTABLE_H */
