/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf 9375 2004-02-02 19:06:54Z rstory $
 */
#ifndef SYSORTABLE_H
#define SYSORTABLE_H

/* function declarations */
void init_sysORTable(void);
void initialize_table_sysORTable(void);
Netsnmp_Node_Handler sysORTable_handler;

/* column number definitions for table sysORTable */
       #define COLUMN_SYSORINDEX		1
       #define COLUMN_SYSORID		2
       #define COLUMN_SYSORDESCR		3
       #define COLUMN_SYSORUPTIME		4
#endif /* SYSORTABLE_H */
