// COPYRIGHT_BEGIN
//  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
//  
//  Copyright (C) 2008-2013, Cable Television Laboratories, Inc. 
//  
//  This software is available under multiple licenses: 
//  
//  (1) BSD 2-clause 
//   Redistribution and use in source and binary forms, with or without modification, are
//   permitted provided that the following conditions are met:
//        ·Redistributions of source code must retain the above copyright notice, this list 
//             of conditions and the following disclaimer.
//        ·Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
//             and the following disclaimer in the documentation and/or other materials provided with the 
//             distribution.
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
//   TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
//   PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
//   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
//   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
//   THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  
//  (2) GPL Version 2
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, version 2. This program is distributed
//   in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
//   even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//   PURPOSE. See the GNU General Public License for more details.
//  
//   You should have received a copy of the GNU General Public License along
//   with this program.If not, see<http:www.gnu.org/licenses/>.
//  
//  (3)CableLabs License
//   If you or the company you represent has a separate agreement with CableLabs
//   concerning the use of this code, your rights and obligations with respect
//   to this code shall be as set forth therein. No license is granted hereunder
//   for any other purpose.
//  
//   Please contact CableLabs if you need additional information or 
//   have any questions.
//  
//       CableLabs
//       858 Coal Creek Cir
//       Louisville, CO 80027-9750
//       303 661-9100
// COPYRIGHT_END

package org.ocap.hardware.device;

import org.dvb.media.VideoFormatControl;
import org.havi.ui.HScreenConfigTemplate;
import org.havi.ui.HVideoConfigTemplate;
import org.havi.ui.HVideoConfiguration;

/**
 * An interface that defines the constants that can be used for specifying zoom
 * mode preferences in an HVideoConfigTemplate.
 * 
 * @see VideoFormatControl
 * @see HVideoConfigTemplate
 */
public interface VideoZoomPreference
{
    /**
     * A value for use in the preference field of the
     * {@link HVideoConfigTemplate#setPreference(int, Object, int)
     * setPreference}, {@link HVideoConfigTemplate#getPreferenceObject
     * getPreferenceObject} and
     * {@link HVideoConfigTemplate#getPreferencePriority getPreferencePriority}
     * methods in the {@link HVideoConfigTemplate} that indicates that the
     * <code>HVideoConfiguration</code> implies a specific decoder format
     * conversion as specified in an <code>Integer</code> object. Valid
     * preference objects for this preference are instances of
     * <code>Integer</code> to be interpreted as a decoder format conversion
     * constant for the profile (e.g., one of the VideoFormatControl
     * {@link VideoFormatControl DFC_* constants}).
     * <p>
     * The <code>ZOOM_MODE</code> preference SHALL be applied to convert input
     * video with one aspect ratio when presented on a full-screen
     * <code>HVideoDevice</code> with another display aspect ratio when not
     * overridden by an application-directed setting. That is, the
     * <code>ZOOM_MODE</code> preference setting for the HVideoDevice is applied
     * by default for newly created JMF Players or when
     * {@link VideoFormatControl#DFC_PLATFORM} is the current decoder format
     * conversion setting for a JMF <code>Player</code>.
     * <p>
     * Instances of {@link HVideoConfigTemplate} generated by the platform and
     * returned to applications (e.g., from
     * {@link HVideoConfiguration#getConfigTemplate()} SHALL have this
     * preference set to a valid platform-supported DFC constant (as an instance
     * of <code>Integer</code>) with {@link HScreenConfigTemplate#REQUIRED
     * REQUIRED} priority.
     */
    public static final int ZOOM_MODE = 0x2001;

}
