// COPYRIGHT_BEGIN
//  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
//  
//  Copyright (C) 2008-2013, Cable Television Laboratories, Inc. 
//  
//  This software is available under multiple licenses: 
//  
//  (1) BSD 2-clause 
//   Redistribution and use in source and binary forms, with or without modification, are
//   permitted provided that the following conditions are met:
//        ·Redistributions of source code must retain the above copyright notice, this list 
//             of conditions and the following disclaimer.
//        ·Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
//             and the following disclaimer in the documentation and/or other materials provided with the 
//             distribution.
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
//   TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
//   PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
//   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
//   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
//   THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  
//  (2) GPL Version 2
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, version 2. This program is distributed
//   in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
//   even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//   PURPOSE. See the GNU General Public License for more details.
//  
//   You should have received a copy of the GNU General Public License along
//   with this program.If not, see<http:www.gnu.org/licenses/>.
//  
//  (3)CableLabs License
//   If you or the company you represent has a separate agreement with CableLabs
//   concerning the use of this code, your rights and obligations with respect
//   to this code shall be as set forth therein. No license is granted hereunder
//   for any other purpose.
//  
//   Please contact CableLabs if you need additional information or 
//   have any questions.
//  
//       CableLabs
//       858 Coal Creek Cir
//       Louisville, CO 80027-9750
//       303 661-9100
// COPYRIGHT_END

package org.ocap.shared.dvr;

import javax.tv.service.selection.ServiceContext;
import javax.tv.service.selection.ServiceContextEvent;

/**
 * An Event Notifying that recording has terminated for the
 * <code>ServiceContext</code>. This event is generated by a
 * <code>ServiceContext</code> that is presenting a time-shifted service or a
 * service that is being recorded. The presentation is not yet terminated as the
 * playback point is time-delayed. This event is generated only when the
 * playback point is not the same as the live point. A
 * <code>PresentationTerminatedEvent</code> will be generated when the playback
 * point catches up with the point of record termination.
 */
public class RecordingTerminatedEvent extends ServiceContextEvent
{
    /**
     * Reason code: The service vanished from the network.
     */
    public static final int SERVICE_VANISHED = 1;

    /**
     * Reason code: Resources needed to record the service have been removed.
     * Will be generated if the {@link ServiceContext} stop method is called.
     */
    public static final int RESOURCES_REMOVED = 2;

    /**
     * Reason code: Access to the service or some component of it has been
     * withdrawn by the system. An example of this is the end of a free preview
     * period for IPPV content.
     */
    public static final int ACCESS_WITHDRAWN = 3;

    /**
     * Reason code: The recording was terminated normally as scheduled.
     */
    public static final int SCHEDULED_STOP = 4;

    /**
     * Reason code: The user requested that the recording be stopped. Also, if
     * the {@link RecordingRequest} stop method is called.
     */
    public static final int USER_STOP = 5;

    /**
     * Constructs the event.
     *
     * @param source
     *            The <code>ServiceContext</code> that generated the event.
     */
    public RecordingTerminatedEvent(ServiceContext source, int reason)
    {
        super(source);
        this.reason = reason;
    }

    /**
     * Returns the reason for the recordings termination.
     *
     * @return Termination reason; see constants in this class.
     */
    public int getReason()
    {
        return reason;
    }

    private final int reason;
}
