// COPYRIGHT_BEGIN
//  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
//  
//  Copyright (C) 2008-2013, Cable Television Laboratories, Inc. 
//  
//  This software is available under multiple licenses: 
//  
//  (1) BSD 2-clause 
//   Redistribution and use in source and binary forms, with or without modification, are
//   permitted provided that the following conditions are met:
//        ·Redistributions of source code must retain the above copyright notice, this list 
//             of conditions and the following disclaimer.
//        ·Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
//             and the following disclaimer in the documentation and/or other materials provided with the 
//             distribution.
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
//   TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
//   PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
//   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
//   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
//   THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  
//  (2) GPL Version 2
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, version 2. This program is distributed
//   in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
//   even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//   PURPOSE. See the GNU General Public License for more details.
//  
//   You should have received a copy of the GNU General Public License along
//   with this program.If not, see<http:www.gnu.org/licenses/>.
//  
//  (3)CableLabs License
//   If you or the company you represent has a separate agreement with CableLabs
//   concerning the use of this code, your rights and obligations with respect
//   to this code shall be as set forth therein. No license is granted hereunder
//   for any other purpose.
//  
//   Please contact CableLabs if you need additional information or 
//   have any questions.
//  
//       CableLabs
//       858 Coal Creek Cir
//       Louisville, CO 80027-9750
//       303 661-9100
// COPYRIGHT_END

/* Generated by Together */

package org.cablelabs.impl.awt;

import java.awt.AWTEvent;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.awt.KeyEventDispatcher;
import java.awt.KeyEventPostProcessor;
import java.awt.event.KeyEvent;

import java.beans.PropertyChangeListener;
import java.beans.VetoableChangeListener;

import java.util.Set;

/**
 * 
 * @author Greg Rutz
 */
abstract public class KeyboardFocusManager
{
    private java.awt.KeyboardFocusManager awtKeyboardFocusManager;

    /**
     * Returns the AWT <code>KeyboardFocusManager</code> object associated with
     * this implementation object
     * 
     * @return the AWT KFM
     */
    public java.awt.KeyboardFocusManager getAWTKeyboardFocusManager()
    {
        return awtKeyboardFocusManager;
    }

    /**
     * Sets the AWT <code>KeyboardFocusManager</code> object associated with
     * this implementation object
     * 
     * @param awtKFM
     *            the AWT KFM
     */
    public void setAWTKeyboardFocusManager(java.awt.KeyboardFocusManager awtKFM)
    {
        awtKeyboardFocusManager = awtKFM;
    }

    /**
     * Methods overriding java.awt.KeyboardFocusManager methods
     */

    abstract public boolean requestFocus(Component c, boolean temporary);

    abstract public Component getFocusOwner();

    abstract public void clearGlobalFocusOwner();

    abstract public Component getPermanentFocusOwner();

    abstract public FocusTraversalPolicy getDefaultFocusTraversalPolicy();

    abstract public void setDefaultFocusTraversalPolicy(FocusTraversalPolicy policy);

    abstract public Set getDefaultFocusTraversalKeys(int id);

    abstract public void setDefaultFocusTraversalKeys(int id, Set keystrokes);

    abstract public Container getCurrentFocusCycleRoot();

    abstract public void addPropertyChangeListener(PropertyChangeListener listener);

    abstract public void removePropertyChangeListener(PropertyChangeListener listener);

    abstract public void addVetoableChangeListener(VetoableChangeListener listener);

    abstract public void removeVetoableChangeListener(VetoableChangeListener listener);

    abstract public void addKeyEventDispatcher(KeyEventDispatcher dispatcher);

    abstract public void removeKeyEventDispatcher(KeyEventDispatcher dispatcher);

    abstract public void addKeyEventPostProcessor(KeyEventPostProcessor processor);

    abstract public void removeKeyEventPostProcessor(KeyEventPostProcessor processor);

    abstract public boolean dispatchEvent(AWTEvent e);

    abstract public boolean dispatchKeyEvent(KeyEvent e);

    abstract public boolean postProcessKeyEvent(KeyEvent e);

    abstract public void processKeyEvent(Component focusedComponent, KeyEvent e);

    abstract public void focusNextComponent(Component c);

    abstract public void focusPreviousComponent(Component c);

    abstract public void upFocusCycle(Component c);

    abstract public void downFocusCycle(Container c);
}
